<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\FiliereController;
use App\Http\Controllers\EnseignantController;
use App\Http\Controllers\SalleController;
use App\Http\Controllers\MatiereController;
use App\Http\Controllers\CreneauController;
use App\Http\Controllers\EmploiDuTempsController;
use App\Http\Controllers\EtudiantController;

// -------------------------------------------------------
// PUBLIC — landing page (no login required)
// -------------------------------------------------------
Route::get('/', function () {
    $stats = [
        'filieres' => \App\Models\Filiere::count(),
        'enseignants' => \App\Models\Enseignant::count(),
        'salles' => \App\Models\Salle::count(),
        'cours' => \App\Models\EmploiDuTemps::count(),
    ];
    return view('welcome', compact('stats'));
})->name('home');

// -------------------------------------------------------
// AUTH ROUTES — generated by Breeze (login, register, etc.)
// -------------------------------------------------------
require __DIR__.'/auth.php';

// -------------------------------------------------------
// PROTECTED — all routes below require login
// -------------------------------------------------------
Route::middleware(['auth'])->group(function () {

    // Dashboard — accessible by all logged-in users
    Route::get('/dashboard', [DashboardController::class, 'index'])
        ->name('dashboard');

    // -------------------------------------------------------
    // STUDENT VIEW — read-only timetable filtered by filiere
    // -------------------------------------------------------
    Route::middleware(['role:etudiant,admin'])->group(function () {
    
    // Export MUST be first
    Route::get('/mon-emploi-du-temps/export', [EtudiantController::class, 'export'])
        ->name('etudiant.export');

    Route::get('/mon-emploi-du-temps', [EtudiantController::class, 'index'])
        ->name('etudiant.emploi');

    Route::get('/mon-emploi-du-temps/{filiere}', [EtudiantController::class, 'show'])
        ->name('etudiant.emploi.show');
});

        // -------------------------------------------------------
    // TEACHER VIEW — personal schedule
    // -------------------------------------------------------
    Route::middleware(['role:enseignant,admin'])->group(function () {
        Route::get('/mon-planning', [EnseignantController::class, 'planning'])
            ->name('enseignants.planning');
        
        
        // Export timetable as PDF for a specific filiere
        Route::get('/emplois/export/{filiere}', [EmploiDuTempsController::class, 'export'])
            ->name('emplois.export');

        Route::get('/mon-planning/export', [EnseignantController::class, 'exportPlanning'])
        ->name('enseignants.export');
    });

    // -------------------------------------------------------
    // ADMIN ONLY — full CRUD
    // -------------------------------------------------------
    Route::middleware(['role:admin'])->group(function () {

        // Filieres
        Route::resource('filieres', FiliereController::class);

        // Enseignants
        Route::resource('enseignants', EnseignantController::class);

        // Salles
        Route::resource('salles', SalleController::class);

        // Matieres
        Route::resource('matieres', MatiereController::class);

        // Creneaux
        Route::resource('creneaux', CreneauController::class)->parameters([
            'creneaux' => 'creneau'
        ]);

        // Emplois du temps — core resource + extra routes
        Route::resource('emplois', EmploiDuTempsController::class);

        

        // View full timetable grid for a specific filiere (admin preview)
        Route::get('/emplois/filiere/{filiere}', [EmploiDuTempsController::class, 'byFiliere'])
            ->name('emplois.filiere');
    });

});